### ISSUE TITLE
User has a more responsive interaction with the app

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#15]
## 💰 Motivation
User should know if they are clicking a button and adding a quote to favorites.

## 📐 Plan
Add styling to buttons to be responsive to user interaction.

## ✅ Task List
- [x] Add hover features for buttons
- [x] Add active features for buttons
- [x] If a quote or joke exists in favorites, do not allow user to re-favorite the particular text
- [x] If an author is not available for a quote, add 'Anonymous' as the author 
- [x] Test all functionality and fix any errors
