### ISSUE TITLE
User can view app on multiple devices

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#17]
## 💰 Motivation
The user should be able to view the polished application on multiple devices with different screen sized.

## 📐 Plan
Add styling suited for multiple devices.

## ✅ Task List
- [x] Add styling for Galaxy S5 Devices
- [x] Test Features
- [x] Add styling for Pixel and Pixel XL devices
- [x] Test Features
- [x] Add styling for iPhone 5/SE
- [x] Test Features
- [x] Add styling for iPhone 6/7/8 and iPhone 6/7/8 Plus
- [x] Test Features
- [x] Add styling for iPhone X
- [x] Test Features
- [x] Add styling for tablets
- [x] Test Features
- [x] Remove styling that isn't doing anything
