### ISSUE TITLE
Hover animations for buttons and icons

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#19]
## 💰 Motivation
When a user hovers over buttons or icons, there should be animations for interactive styling!

## 📐 Plan
Add styling to buttons and icons when they are being hovered with the users cursor.

## ✅ Task List
- [x] Add transition declarations to buttons and icons for 0.5 seconds to change background color
- [x] Add animation to buttons and icons when they are clicked
- [x] Test functionality for different displays
- [x] Remove styling that isn't doing anything
