### ISSUE TITLE
issue-2-user-can-view-a-list-of-searched-recipes

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#2]
## ⚙️ Feature

After searching keywords for vegan recipes, the user can see a list of recipes!

## 📐 Functionality

When the user clicks on the search feature, after entering keywords, a list of blocks containing an image, title, calorie count, and time will be rendered for the user to view.

### Mobile:
![image](https://user-images.githubusercontent.com/76730244/172901736-32cf5613-a559-4af0-bd57-71e5b7112127.png)

### Desktop:
![image](https://user-images.githubusercontent.com/76730244/172901775-a9d6159f-72e0-46ba-b8bf-082a21134912.png)

## ✅ Task List

- [x] Create a section element for the Recipe Card
- [x] Create a dummy card for styling
  - [x] Update card styling to match figma
- [x] Copy the dummy card
  - [x] Add the dummy card to the main.js file as a template
  - [x] Comment out the dummy card   
- [x] Create an event listener for page load
  - [x] Ensure that the user sees the search feature on page load
  **Define a function that will**
  - [x] Take the array filled with objects of recipe information and rendor the following:
    - [x] Image
    - [x] Title
    - [x] Calories
    - [x] Time
- [x] Update styling to match figma for both mobile and desktop
  - [x] Use @media querys to change flexbox orientation
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
