### ISSUE TITLE
Design Update: User can view full recipe

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#20]
## ⚙️ Feature

When the user clicks on a recipe card, they should be able to see a full recipe. Currently, we have a return error.

## 📐 Plan

Refactor renderRecipe function definition to support the new, public, Meal Database API

## 🖼️ Wireframes

WIP

## ✅ Task List

- [x] Refactor renderRecipe function definition to
- [x] Define a local local method to display ingredients and amounts for the recipe
- [x] Refactor instructions render
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
