### ISSUE TITLE
User will see a loading spinner when AJAX requests are sent out

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#21]
## 💰 Motivation
The user will know when the API's are being loaded for their Quotes and Jokes!

## 📐 Plan
Add a modal for a loading spinner when AJAX requests are being sent out, then it will be hidden when the AJAX response comes back

## ✅ Task List
- [x] Create a hidden modal
- [x] Add a loading spinner to the modal
- [x] The loading modal will display a loading spinner when the AJAX Request is sent out
- [x] The loading modal will be hidden when the AJAX response comes back
- [x] Test functionality with different displays
- [x] Remove CSS that isn't doing anything
