### ISSUE TITLE
Update styling for a better user experience

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#23]
## 💰 Motivation
Styling needs to be more appealing for the user

## 📐 Plan
Update styling and animations for a better user experience

## ✅ Task List
- [x] Re-style border radius for text boxes
- [x] Update positioning to be more consistent 
- [x] Remove text-shadow and change font-color to dark gray where needed
- [x] Resize header for font spacing
- [x] Change "else Laugh" font styling
- [x] Change font sizes or weights for the authors of the quotes
- [x] Modify quote/joke box sizing
- [x] Speed up animations
