### ISSUE TITLE
User can sign up or log in

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#25]
## 💰 Motivation
Sometimes it's hard to pick a movie. This app is designed to help the push making a decision on what movie to watch instead of scrolling through Netflix for 20 minutes before picking something.

## 📐 Plan
Created an interface and allow the user to register, then sign in with the created account.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/113760200-f52c5d00-96e3-11eb-9333-779dc92568ec.png)

## ✅ Task List
- [ ] Create HTML Skeleton
- [ ] Create a for the app
- [ ] Add styling to match the wireframe
- [ ] Save styling and layout for react files
- [ ]
