### ISSUE TITLE
issue-3-user-can-view-recipe-information

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#3]
## ⚙️ Feature

User can click on a recipe card, this action will display the instructions and ingredient measurements!

## 📐 Functionality

When the user is viewing a list of recipes, they will need information. Each list element will be clickable and will render data that was pushed into an array by searching keywords of ingredients. This data will be thorough in showing the user what all of the ingredients are.

### Mobile:
![image](https://user-images.githubusercontent.com/76730244/172962915-b012cc5a-dbb0-436b-9a3a-00ba4e8efd6c.png)

### Desktop:
![image](https://user-images.githubusercontent.com/76730244/172962890-0be45fc2-fc62-4acd-a762-f6c2db982b25.png)

## ✅ Task List

- [x] Create a section for the recipe
- [x] Create a div that will contain
  - [x] A div for the image
  - [x] A div for the title
- [x] Create a div that will contain
  - [x] A div for the summary of the recipe
  - [x] A div containing a list of ingredients for the recipe
- [x] Create a div that will contain
  - [x] A div for the Instructions Button   
  - [x] A div for the save recipe button
- [x] Create a div that will contain
  - [x] A div for the nutrition button
  - [x] A div for the back to list button
- [x] Style all elements to replicate the figma
  - [x] Using @media querys, update layout to adapt to desktop\
- [x] Add a click event listener to all recipes
- **When the user clicks a recipe**
  - [x] Render the element created above and add text content 
    - [x] Add value to the img src attribute
    - [x] Add value to the title element
    - [x] Add value to the summary element
    - [x] Add value to the ingredient element
- [x] Add a click event listener to the buttons
  - [x] instructions
  - [x] save recipe
  - [x] nutrition
  - [x] back to list 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
