### ISSUE TITLE
issue-4-user-can-view-nutrition-values-of-recipe

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#4]
## ⚙️ Feature

Some users who are following a diet, or have diet restrictions or allergies, will want to see a detailed nutrition list that will inform them of what is in the recipe!

## 📐 Functionality

When the user is viewing the detailed information about the recipe, they can click a 'Nutrition' button that will open a modal and present a list of nutrition information.

### Mobile:
![image](https://user-images.githubusercontent.com/76730244/172973011-a516aa4d-bce4-4cb0-8194-c2ebb8e28afa.png)

### Desktop:
![image](https://user-images.githubusercontent.com/76730244/172973053-9fdf1722-e2ca-4836-95e0-a69c21d4686c.png)

## ✅ Task List

- [ ] Create a div with absolute positioning and set
  - [ ] top: 0
  - [ ] bottom: 0
  - [ ] left: 0
  - [ ] right: 0
- [ ] Set background color to white and opacity at 70%  
- [ ] Create a div that will contain a list of ingredients
- **Add to the click event listener on the nutrition button**
  - [ ] Create a list by looping through the arary
  - [ ] Update the text content with nutritional values for each object in the array
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Create a Close button
- [ ] Add a click event listener that will close the nutrion modal
- [ ] When the nutrition modal is closed, the user will see the recipe they were viewing
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
