### ISSUE TITLE
issue-5-user-can-view-recipe-instructions

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#5]
## ⚙️ Feature

The user can see detailed information about the recipe, including nutrition! This is great! The user still needs to know how to cook it. By clicking a button labeled Instructions, the user will be taken to an absolute URL in a new tab displaying a step-by-step guide of the process!

## 📐 Functionality

User can view the instructions for the recipe by clicking a button that will open the instructions in a new tab.

### Mobile:
![image](https://user-images.githubusercontent.com/76730244/172975119-2e21b2b7-f135-48ae-bf5f-4ec30ef24afd.png)

### Desktop:
![image](https://user-images.githubusercontent.com/76730244/172975463-d0f40a40-1296-4e1a-ad36-0c5e24a6d9e8.png)

## ✅ Task List

-**For the instructions button**
  - [ ] add a target attribute and set the value to '__blank'
  - [ ] update the element to contain an absolute URL path to the instructions string value in the array
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
