### ISSUE TITLE
bug-ajax-call-returning-non-vegan-recipes

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/ajax-project#8]
## 🐛 Bug

The search feature should return data with vegan recipes.

The app currently returns any recipe for any diet.

## ✅ Task List

**Update the AJAX Call function**
  - [x] xhr.open call with the 2nd argument needs to be updated
  - [x] test api calls by modifying the string in the 2nd argument until strictly vegan data is returned
  - [x] update xhr.open call to allow searching of ingredients in vegan diets
**Update the renderRecipeCards function**
  - [x] Use a dummy call and console.log the data returned
  - [x] Copy data and paste into the main js file
  - [x] Comment out the data
  - [x] Use data as a reference to update renderRecipeCards function:
    - [x] Image
    - [x] Title
    - [x] Time
    - [x] Calories 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
